baseurl = "https://allanregush@github.io"
title = "Blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Allan Regush"
    description = "A Programmer's Blog"
    github = "https://github.com/AllanRegush"
    twitter = "https://twitter.com/AllanRegush"
    linkedin = "https://linkedin.com/in/allanregush"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[[menu.main]]
    name = 'Blog'
    url =  '/'
    weight = 1
[[menu.main]]
    name = 'Projects'
    url = '/project/'
    weight = 1
[[menu.main]]
    name = 'Contact'
    url = '/page/contact/'
    weight = 3
[[menu.main]]
    name = 'About'
    url = '/page/about/'
    weight = 4




[Permalinks]
    post = "/:filename/"